# ⚙️ Data Preprocessing

## Personalized Healthcare & Medicine Recommendation System

This notebook performs data preprocessing tasks such as handling missing values, encoding categorical variables, feature engineering, data scaling, and preparing the dataset for machine learning models.

## Step 1: Import Required Libraries

Import all the necessary libraries required for data preprocessing and feature engineering.

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

print("Libraries imported successfully!")

Libraries imported successfully!

## Step 2: Load the Dataset

Load the healthcare dataset for preprocessing and transformation.

In [2]:
df = pd.read_csv("../../data/raw/Cleaned_Dataset.csv")

df.head()

,disease,fever,cough,fatigue,difficulty_breathing,age,gender,blood_pressure,cholesterol_level,outcome_variable,age_scaled,bp_scaled,chol_scaled,risk_level
0,Influenza,Yes,No,Yes,Yes,19,female,0,1,Positive,-2.091160,-2.419529,-0.576777,Low
1,Common Cold,No,Yes,Yes,No,25,female,1,1,Negative,-1.631964,-0.723915,-0.576777,Low
2,Eczema,No,Yes,Yes,No,25,female,1,1,Negative,-1.631964,-0.723915,-0.576777,Medium
3,Asthma,Yes,Yes,No,Yes,25,male,1,1,Positive,-1.631964,-0.723915,-0.576777,Medium
4,Asthma,Yes,Yes,No,Yes,25,male,1,1,Positive,-1.631964,-0.723915,-0.576777,Medium

## Step 3: Dataset Overview

Display information about the dataset, including data types, number of records, and missing values.

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 349 entries, 0 to 348
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   disease               349 non-null    str
 1   fever                 349 non-null    str
 2   cough                 349 non-null    str
 3   fatigue               349 non-null    str
 4   difficulty_breathing  349 non-null    str
 5   age                   349 non-null    int64
 6   gender                349 non-null    str
 7   blood_pressure        349 non-null    int64
 8   cholesterol_level     349 non-null    int64
 9   outcome_variable      349 non-null    str
 10  age_scaled            349 non-null    float64
 11  bp_scaled             349 non-null    float64
 12  chol_scaled           349 non-null    float64
 13  risk_level            349 non-null    str
dtypes: float64(3), int64(3), str(8)
memory usage: 38.3 KB

## Step 4: Missing Value Analysis

Check whether the dataset contains any missing values before preprocessing.

In [4]:
df.isnull().sum()

disease                 0
fever                   0
cough                   0
fatigue                 0
difficulty_breathing    0
age                     0
gender                  0
blood_pressure          0
cholesterol_level       0
outcome_variable        0
age_scaled              0
bp_scaled               0
chol_scaled             0
risk_level              0
dtype: int64

## Step 5: Duplicate Record Analysis

Identify duplicate records present in the dataset.

In [5]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 49

## Step 6: Remove Duplicate Records

Remove duplicate records to improve data quality before model training.

In [6]:
df = df.drop_duplicates()

print("Dataset Shape:", df.shape)

Dataset Shape: (300, 14)

## Step 7: Encode Categorical Features

Machine learning models require numerical input. In this step, all categorical features such as disease, gender, symptoms, blood pressure, cholesterol level, and outcome are converted into numerical values using Label Encoding.

In [7]:
from sklearn.preprocessing import LabelEncoder
import joblib
import os

label_encoders = {}

categorical_columns = df.select_dtypes(include=['object']).columns

for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

os.makedirs("../../models", exist_ok=True)

joblib.dump(label_encoders["disease"], "../../models/disease_label_encoder.pkl")

print("Disease Label Encoder Saved Successfully!")

df.head()

C:\Users\Shreya\AppData\Local\Temp\ipykernel_20896\3932699795.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns

Disease Label Encoder Saved Successfully!

,disease,fever,cough,fatigue,difficulty_breathing,age,gender,blood_pressure,cholesterol_level,outcome_variable,age_scaled,bp_scaled,chol_scaled,risk_level
0,56,1,0,1,1,19,0,0,1,1,-2.091160,-2.419529,-0.576777,1
1,24,0,1,1,0,25,0,1,1,0,-1.631964,-0.723915,-0.576777,1
2,37,0,1,1,0,25,0,1,1,0,-1.631964,-0.723915,-0.576777,2
3,6,1,1,0,1,25,1,1,1,1,-1.631964,-0.723915,-0.576777,2
5,37,1,0,0,0,25,0,1,1,1,-1.631964,-0.723915,-0.576777,2

## Step 8: Verify Encoded Dataset

After encoding, verify that all categorical columns have been successfully converted into numerical data types.

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 300 entries, 0 to 347
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   disease               300 non-null    int64
 1   fever                 300 non-null    int64
 2   cough                 300 non-null    int64
 3   fatigue               300 non-null    int64
 4   difficulty_breathing  300 non-null    int64
 5   age                   300 non-null    int64
 6   gender                300 non-null    int64
 7   blood_pressure        300 non-null    int64
 8   cholesterol_level     300 non-null    int64
 9   outcome_variable      300 non-null    int64
 10  age_scaled            300 non-null    float64
 11  bp_scaled             300 non-null    float64
 12  chol_scaled           300 non-null    float64
 13  risk_level            300 non-null    int64
dtypes: float64(3), int64(11)
memory usage: 35.2 KB

## Step 9: Feature Scaling

Feature scaling standardizes numerical features to ensure that all variables contribute equally during model training.

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_columns = ['age']

df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

df.head()

,disease,fever,cough,fatigue,difficulty_breathing,age,gender,blood_pressure,cholesterol_level,outcome_variable,age_scaled,bp_scaled,chol_scaled,risk_level
0,56,1,0,1,1,-2.127676,0,0,1,1,-2.091160,-2.419529,-0.576777,1
1,24,0,1,1,0,-1.650559,0,1,1,0,-1.631964,-0.723915,-0.576777,1
2,37,0,1,1,0,-1.650559,0,1,1,0,-1.631964,-0.723915,-0.576777,2
3,6,1,1,0,1,-1.650559,1,1,1,1,-1.631964,-0.723915,-0.576777,2
5,37,1,0,0,0,-1.650559,0,1,1,1,-1.631964,-0.723915,-0.576777,2

## Step 10: Separate Features and Target Variable

Before training a machine learning model, the dataset is divided into input features (X) and the target variable (y). The model learns from the input features to predict the target variable.

In [10]:
print(df.columns)

Index(['disease', 'fever', 'cough', 'fatigue', 'difficulty_breathing', 'age',
       'gender', 'blood_pressure', 'cholesterol_level', 'outcome_variable',
       'age_scaled', 'bp_scaled', 'chol_scaled', 'risk_level'],
      dtype='str')

In [11]:
X = df.drop('outcome_variable', axis=1)
y = df['outcome_variable']

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (300, 13)
Target Shape: (300,)

## Step 11: Split Dataset into Training and Testing Sets

The dataset is divided into training and testing subsets. The training data is used to train the machine learning model, while the testing data is used to evaluate its performance on unseen data.

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)
print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (240, 13)
Testing Features  : (60, 13)
Training Labels   : (240,)
Testing Labels    : (60,)

## Step 12: Save the Processed Dataset

After preprocessing, the cleaned dataset is saved for use in machine learning model development.

In [13]:
df.to_csv("../../data/processed/processed_dataset.csv", index=False)

print("✅ Processed dataset saved successfully!")

✅ Processed dataset saved successfully!

# ✅ Data Preprocessing Summary

### Completed Tasks

- Imported the required libraries.
- Loaded the healthcare dataset.
- Examined the dataset structure and data types.
- Checked for missing values and duplicate records.
- Encoded categorical variables into numerical values.
- Applied feature scaling to numerical attributes.
- Separated input features and target variable.
- Split the dataset into training and testing sets.
- Saved the processed dataset for machine learning.

## Conclusion

The dataset has been successfully preprocessed and is now ready for machine learning model training and evaluation.